//! Generated gateway bootstrap for sdkwork-memory.
//! Regenerated by pnpm gateway:assembly:materialize.

use axum::Router;
use std::sync::Arc;

pub struct ApplicationAssembly {
    pub router: Router,
}

pub fn assemble_application_router() -> ApplicationAssembly {
    let mut router = Router::new();
    router = router.merge(sdkwork_routes_memory_app_api::gateway_mount(api));
    router = router.merge(sdkwork_routes_memory_backend_api::gateway_mount(api));
    router = router.merge(sdkwork_routes_memory_open_api::gateway_mount(api));
    ApplicationAssembly { router }
}
