#!/usr/bin/env node
/**
 * Materialize database/ddl/baseline from the native-sql plugin authority.
 *
 * Initialization state (pre-GA): plugin migrations are folded into
 * database/ddl/baseline/{engine}/0001_memory_baseline.sql. The application-root
 * database/migrations/{engine}/ tree stays empty except README placeholders.
 *
 * Post-GA schema changes: author new V*.sql files in the plugin, then add numbered
 * .up.sql/.down.sql pairs under database/migrations/{engine}/ only.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import crypto from "node:crypto";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

const pluginMigrationOrder = [
  "V202606100001__memory_phase1.sql",
  "V202606100002__memory_phase1_indexes.sql",
  "V202606230001__mem_tenant_preference.sql",
  "V202606240001__ai_learning_job.sql",
  "V202606240002__ai_record_fulltext_search.sql",
  "V202606250001__ai_eval_run_extend.sql",
  "V202606250002__memory_commercial_management.sql",
];

function writeBaseline(engine) {
  const sections = [
    `-- SDKWork memory consolidated initialization baseline (${engine})`,
    `-- Generated by tools/materialize_memory_migrations.mjs`,
    `-- Initialization state: full DDL lives here; database/migrations/${engine}/ is post-GA only.`,
    "",
  ];

  for (const source of pluginMigrationOrder) {
    const from = path.join(
      root,
      "plugins/sdkwork-memory-plugin-native-sql/migrations",
      engine,
      source,
    );
    if (!fs.existsSync(from)) {
      throw new Error(`missing plugin migration source: ${from}`);
    }
    const sql = fs.readFileSync(from, "utf8").trim();
    sections.push(
      `-- source: plugins/sdkwork-memory-plugin-native-sql/migrations/${engine}/${source}`,
    );
    sections.push(sql);
    sections.push("");
  }

  const relativePath = path.join(
    "database/ddl/baseline",
    engine,
    "0001_memory_baseline.sql",
  );
  const absolutePath = path.join(root, relativePath);
  fs.mkdirSync(path.dirname(absolutePath), { recursive: true });
  const output = `${sections.join("\n").trim()}\n`;
  fs.writeFileSync(absolutePath, output);
  const digest = crypto.createHash("sha256").update(output).digest("hex");
  process.stdout.write(
    `materialized ${relativePath} (sha256:${digest.slice(0, 12)})\n`,
  );
}

for (const engine of ["postgres", "sqlite"]) {
  writeBaseline(engine);
}
